version: '3'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - my-db:/var/lib/mysql

  app:
    image: 4408fd445b68
    ports: 
    - "8080:80"

volumes:
  my-db:
